/*===================================================================================================
                      Copyright(C) 1997-2099.  Midea  EA. Co., Ltd.
-----------------------------------------------------------------------------------------------------
Project Name  : IO_Map.h
Description   : H
Author        : chenglinyu
Start Date    : 2021/9/6 14:43:35
Version       : V1.0
Revision History   1:
                   2:
===================================================================================================*/

#ifndef _IO_MAP_H_
#define _IO_MAP_H_


// -Start- code generated by IT software


#define    P_SEG5_PWMMODE()             P44_PWMMODE()
#define    P_SEG5_ADMODE()              P44_ADMODE()
#define    P_SEG5_INMODE()              P44_INMODE()
#define    P_SEG5_OUTMODE()             P44_OUTMODE()
#define    P_SEG5_SETB()                P44_SETB()
#define    P_SEG5_CLRB()                P44_CLRB()
#define    P_SEG5_READ()                P44_READ()
#define    P_SEG5_ENPULL()              P44_ENPULL()
#define    P_SEG5_DISPULL()             P44_DISPULL()
#define    P_SEG5_ON()                  P44_SETB()
#define    P_SEG5_OFF()                 P44_CLRB()


#define    P_SEG6_PWMMODE()             P25_PWMMODE()
#define    P_SEG6_ADMODE()              P25_ADMODE()
#define    P_SEG6_INMODE()              P25_INMODE()
#define    P_SEG6_OUTMODE()             P25_OUTMODE()
#define    P_SEG6_SETB()                P25_SETB()
#define    P_SEG6_CLRB()                P25_CLRB()
#define    P_SEG6_READ()                P25_READ()
#define    P_SEG6_ENPULL()              P25_ENPULL()
#define    P_SEG6_DISPULL()             P25_DISPULL()
#define    P_SEG6_ON()                  P25_SETB()
#define    P_SEG6_OFF()                 P25_CLRB()


#define    P0_PWMMODE_INIT              0x0     // b0000,0000



// -End- code generated by IT software


#endif
/*===================================================================================================
'2021/9/6 14:43:35        
                                               END

===================================================================================================*/ 
